nj:
  name: namjune
  age: ${random.int(0,100)}
  fullName: ${nj.name} Kim
  sessionTimeout: 30

spring:
  profiles:
    active: prod

  output:
    ansi:
      enabled: always

logging:
  path: logs
  level:
    io.namjune.springbootconceptandutilization: INFO